### ISSUE TITLE
pas de majusculte majuscule c'est pour les class

### ISSUE THREAD

**Issue by Teo3tc** [patoche62500/Print-it#1]
https://github.com/patoche62500/Print-it/blob/ea0ee04e9c962e842c81b21a271b2cd069a2b79b/assets/script.js#L68C21-L68C21

**Comment by Teo3tc** [comment]
slides.forEach((Element) => {
  const dot = document.createElement("div");
  if (Element == slides[0]) {
    dot.className = "dot dot_selected";
  } else {
    dot.className = "dot";
  }

**Comment by Teo3tc** [comment]
`
slides.forEach((Element) => {
  const dot = document.createElement("div");
  if (Element == slides[0]) {
    dot.className = "dot dot_selected";
  } else {
    dot.className = "dot";
  }`

**Comment by patoche62500** [comment]
Fix Remplacement de "Element" par "element"
